language: python

python:
  - '3.8'

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pytest-cov

# Run linting and tests
before_script:
  - export PYTHONPATH="$(pwd):$PYTHONPATH"

script:
  # - pylint --exit-zero config frp tests
  # - pylint config frp tests
  - pytest -v -rs --cov=frp tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
