language: python

python:
  - '3.7'

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint

# Run linting and tests
script:
  - pylint lib
  - pylint tests
  - pytest -v --cov-report term-missing --cov=lib tests/