data_start_date: 1954-07-07
data_end_date: null

FRED:
  series_params:
    - frequency: m
      series_id: FEDFUNDS
      units: lin
    - aggregation_method: eop
      frequency: m
      series_id: DFF
      units: lin
    - aggregation_method: avg
      frequency: m
      series_id: DFF
      units: lin
    - frequency: q
      series_id: GFDEBTN
      units: lin
    - frequency: q
      series_id: GFDEBTN
      units: pch
    - frequency: q
      series_id: GFDEGDQ188S
      units: lin
    - frequency: q
      series_id: GFDEGDQ188S
      units: pch
    - frequency: m
      series_id: PCE
      units: lin
    - frequency: m
      series_id: PCE
      units: pch
    - frequency: m
      series_id: PCEC96
      units: lin
    - frequency: m
      series_id: PCEC96
      units: pch
    - frequency: q
      series_id: A794RX0Q048SBEA
      units: lin
    - frequency: q
      series_id: A794RX0Q048SBEA
      units: pch
    - frequency: q
      series_id: W790RC1Q027SBEA
      units: lin
    - frequency: q
      series_id: W790RC1Q027SBEA
      units: pch
    - frequency: q
      series_id: NNBGFNQ027S
      units: lin
    - frequency: q
      series_id: NNBGFNQ027S
      units: pch
    - frequency: q
      series_id: NNBGFNQ027S
      units: lin
    - frequency: q
      series_id: NNBGFNQ027S
      units: pch
    - frequency: q
      series_id: TCMDO
      units: lin
    - frequency: q
      series_id: TCMDO
      units: pch
    - frequency: m 
      series_id: WTISPLC
      units: lin 
    - frequency: m 
      series_id: DPCERAM1M225NBEA
      units: lin 
    - frequency: m 
      series_id: USREC
      units: lin 
    
    

USBLS:
  series_params:
    - CUSR0000SA0
    - CUSR0000SA0E
    - CUSR0000SA0LE
    - LNS12300000
    - LNS13000000
    - LNS14000000

OECD:
  series_params:
    - dataset_id: QNA
      dimensions:
        countries:
        - USA
        - OECD
        - G-20
        subject:
        - B1_GE
        measure:
        - VPVOBARSA
        - HVPVOBARSA
        - GPSA
        frequency:
        - Q