categorical features:
- potus
- houseOfRep
- fedChair
numeric features:
- cpi_all_seas
- cpi_all_unadj
- cpi_energy_seas
- cpi_energy_unadj
- cpi_less_energy_seas
- cpi_less_energy_unadj
- empl_pop_ratio_seas
- empl_pop_ratio_unadj
- unempl_level_seas
- unempl_level_unadj
- unempl_rate_seas
- unempl_rate_unadj
- EA19_GDP_gth_rate
- EU27_2020_GDP_gth_rate
- G20_GDP_gth_rate
- G7_GDP_gth_rate
- OECD_GDP_gth_rate
- USA_GDP_gth_rate
- US_debt_share_in_GDP
- US_debt_nominal
- USDCNY
- EURUSD
- GSPC(SP500)
- VIX
- trade_balance_All
- trade_balance_Goods
- trade_balance_Services
- WTI_oil_price
- Non_fin_non_corp_business_inv
- Non_fin_corp_business_inv
- Private_business_domestic_inv
- Non_fin_business_inv_total
- Perso_consumption_evol_m
- Perso_consumption_real_q
- Fed_rate_month_avg_diff
- Fed_rate_month_avg_pct_change
- cpi_all_seas_pct_change
- cpi_all_unadj_pct_change
- cpi_energy_seas_pct_change
- cpi_energy_unadj_pct_change
- cpi_less_energy_seas_pct_change
- cpi_less_energy_unadj_pct_change
- empl_pop_ratio_seas_pct_change
- empl_pop_ratio_unadj_pct_change
- unempl_level_seas_pct_change
- unempl_level_unadj_pct_change
- unempl_rate_seas_pct_change
- unempl_rate_unadj_pct_change
- US_debt_share_in_GDP_pct_change
- US_debt_nominal_pct_change
- USDCNY_pct_change
- EURUSD_pct_change
- VIX_pct_change
- GSPC(SP500)_pct_change
- trade_balance_All_pct_change
- trade_balance_Goods_pct_change
- trade_balance_Services_pct_change
- WTI_oil_price_pct_change
- Perso_consumption_real_q_pct_change
- Non_fin_non_corp_business_inv_pct_change
- Non_fin_corp_business_inv_pct_change
- Private_business_domestic_inv_pct_change
original features:
- Date
- cpi_all_seas
- cpi_all_unadj
- cpi_energy_seas
- cpi_energy_unadj
- cpi_less_energy_seas
- cpi_less_energy_unadj
- empl_pop_ratio_seas
- empl_pop_ratio_unadj
- unempl_level_seas
- unempl_level_unadj
- unempl_rate_seas
- unempl_rate_unadj
- EA19_GDP_gth_rate
- EU27_2020_GDP_gth_rate
- G20_GDP_gth_rate
- G7_GDP_gth_rate
- OECD_GDP_gth_rate
- USA_GDP_gth_rate
- Recession
- US_debt_share_in_GDP
- US_debt_nominal
- USDCNY
- EURUSD
- GSPC(SP500)
- VIX
- potus
- houseOfRep
- fedChair
- trade_balance_All
- trade_balance_Goods
- trade_balance_Services
- WTI_oil_price
- Non_fin_non_corp_business_inv
- Non_fin_corp_business_inv
- Private_business_domestic_inv
- Non_fin_business_inv_total
- Perso_consumption_evol_m
- Perso_consumption_real_q
- Fed_rate_month_avg
- Fed_rate_spot_EOM
- Fed_rate_month_avg_diff
- Fed_rate_month_avg_pct_change
- Fed_rate_month_avg_diff_3_class
- Fed_rate_month_avg_diff_5_class
- Fed_rate_month_avg_diff_9_class
- Fed_rate_month_avg_trend
possible labels:
- Fed_rate_month_avg
- Fed_rate_spot_EOM
- Fed_rate_month_avg_diff
- Fed_rate_month_avg_pct_change
- Fed_rate_month_avg_diff_3_class
- Fed_rate_month_avg_diff_5_class
- Fed_rate_month_avg_diff_9_class
- Fed_rate_month_avg_trend
