EA19_GDP_gth_rate: Growth rate %
EU27_2020_GDP_gth_rate: Growth rate %
EURUSD: Fx rate
FF_growth_rate: Growth rate %
FF_month_avg: Interest rate
FF_month_avg_diff: nominal change in rate
FF_month_avg_pct_change: Growth rate %
FF_spot_EOM: Interest rate
FF_trend_diff: 'categorical: Up, Down, Stable'
FF_trend_pct_change: 'categorical: Up, Down, Stable'
G20_GDP_gth_rate: Growth rate %
G7_GDP_gth_rate: Growth rate %
GSPC(SP500): Index
OECD_GDP_gth_rate: Growth rate %
Recession: Binary
USA_GDP_gth_rate: Growth rate %
USDCNY: Fx rate
US_debt_nominal: M$
US_debt_share_in_GDP: '% of GDP'
VIX: Index
WTI_oil_price: $ per barrel
cpi_all_seas: Index 1982-84=100
cpi_all_unadj: Index 1982-84=100
cpi_energy_seas: Index 1982-84=100
cpi_energy_unadj: Index 1982-84=100
cpi_less_energy_seas: Index 1982-84=100
cpi_less_energy_unadj: Index 1982-84=100
empl_pop_ratio_seas: '% of empl. over US pop.'
empl_pop_ratio_unadj: '% of empl. over US pop.'
fedChair: 1 = Democrat, 0 = Republican
houseOfRep: 1 = Democrat, 0 = Republican
potus: 1 = Democrat, 0 = Republican
trade_balance_All: M$
trade_balance_Goods: M$
trade_balance_Services: M$
unempl_level_seas: 1000' people
unempl_level_unadj: 1000' people
unempl_rate_seas: '%'
unempl_rate_unadj: '%'
